CREATE TABLE venues (
	venue_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	venue_name varchar(255) NOT NULL,
	venue_location varchar(255) NOT NULL
);
CREATE TABLE concerts (
	concert_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	concert_name varchar(255) NOT NULL,
	concert_date date NOT NULL,
	concert_duration_minutes integer NOT NULL,
	concert_level varchar(255) NOT NULL,
	venue_id integer NOT NULL,
	CONSTRAINT concerts_duration_minutes_chk CHECK (concert_duration_minutes > 0),
	CONSTRAINT concerts_venue_id_fk FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE concert_places (
	concert_id integer NOT NULL,
	place_row INT NOT NULL,
	place_num INT NOT NULL,
	place_price numeric(10, 2) NOT NULL,
	PRIMARY KEY (concert_id, place_row, place_num),
	CONSTRAINT audience_places_concert_id_fk FOREIGN KEY (concert_id) REFERENCES concerts(concert_id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT audience_places_price_chk CHECK (place_price >= 0)
);
CREATE TABLE concert_reports (
	report_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	concert_id integer NOT NULL,
	event_date date NOT NULL,
	event_name varchar(255) NOT NULL,
	event_form varchar(255) NOT NULL,
	event_topic varchar(255) NOT NULL,
	event_venue varchar(255) NOT NULL,
	attendees_age_0_14 integer NOT NULL DEFAULT 0,
	attendees_age_15_30 integer NOT NULL DEFAULT 0,
	attendees_age_30_plus integer NOT NULL DEFAULT 0,
	disability_accessibility varchar(255) NOT NULL,
	responsible_person_fio varchar(255) NOT NULL,
	leader_fio varchar(255) NOT NULL,
	notes text,
	CONSTRAINT concert_reports_concert_id_fk FOREIGN KEY (concert_id) REFERENCES concerts(concert_id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT concert_reports_attendees_0_14_chk CHECK (attendees_age_0_14 >= 0),
	CONSTRAINT concert_reports_attendees_15_30_chk CHECK (attendees_age_15_30 >= 0),
	CONSTRAINT concert_reports_attendees_30_plus_chk CHECK (attendees_age_30_plus >= 0)
);