CREATE TABLE venues (
	venue_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	venue_name varchar(255) NOT NULL,
	venue_location varchar(255) NOT NULL,
	venue_accessibility boolean NOT NULL
);
CREATE TABLE concerts (
	concert_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	concert_name varchar(255) NOT NULL,
	concert_date date NOT NULL,
	concert_duration_minutes integer NOT NULL,
	concert_level varchar(255) NOT NULL,
	venue_id integer NOT NULL,
	concert_theme varchar(255) NOT NULL,
	concert_responcible varchar(255) NOT NULL,
	concert_supervisor varchar(255) NOT NULL,
	concert_note varchar(2047),
	CONSTRAINT concerts_duration_minutes_chk CHECK (concert_duration_minutes > 0),
	CONSTRAINT concerts_venue_id_fk FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE concert_places (
	concert_id integer NOT NULL,
	place_row INT NOT NULL,
	place_num INT NOT NULL,
	place_price numeric(10, 2) NOT NULL,
	place_sold boolean NOT NULL,
	place_age INT,
	PRIMARY KEY (concert_id, place_row, place_num),
	CONSTRAINT audience_places_concert_id_fk FOREIGN KEY (concert_id) REFERENCES concerts(concert_id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT audience_places_price_chk CHECK (place_price >= 0)
);