-- Месторасположения
CREATE TABLE locations (
	location_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	location_address varchar(255) NOT NULL
);

-- Типы площадок
CREATE TABLE venue_types (
	venue_type_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	venue_type_name varchar(100) NOT NULL UNIQUE
);

-- Площадки
CREATE TABLE venues (
	venue_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	venue_name varchar(150) NOT NULL,
	location_id integer NOT NULL,
	venue_type_id integer NOT NULL,
	CONSTRAINT venues_location_id_fk FOREIGN KEY (location_id) REFERENCES locations(location_id) ON UPDATE CASCADE ON DELETE RESTRICT,
	CONSTRAINT venues_venue_type_id_fk FOREIGN KEY (venue_type_id) REFERENCES venue_types(venue_type_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Концерты
CREATE TABLE concerts (
	concert_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	concert_name varchar(150) NOT NULL,
	concert_date date NOT NULL,
	concert_duration_minutes integer NOT NULL,
	venue_id integer NOT NULL,
	CONSTRAINT concerts_duration_minutes_chk CHECK (concert_duration_minutes > 0),
	CONSTRAINT concerts_venue_id_fk FOREIGN KEY (venue_id) REFERENCES venues(venue_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Места зрителей
CREATE TABLE audience_places (
	place_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	concert_id integer NOT NULL,
	place_name varchar(100) NOT NULL,
	place_capacity integer NOT NULL,
	place_price numeric(10, 2) NOT NULL,
	sold_places integer NOT NULL,
	CONSTRAINT audience_places_concert_id_fk FOREIGN KEY (concert_id) REFERENCES concerts(concert_id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT audience_places_capacity_chk CHECK (place_capacity >= 0),
	CONSTRAINT audience_places_price_chk CHECK (place_price >= 0),
	CONSTRAINT audience_places_sold_chk CHECK (sold_places >= 0 AND sold_places <= place_capacity)
);
