---
author: "Андреев Егор Сергеевич"
format: pdf
sansfont: "Times New Roman"
mainfont: "Times New Roman"
geometry: top=1cm, bottom=1cm, left=1cm, right=1cm
fontsize: "14"
header-includes:
  - \usepackage{array} # Table border
  - \usepackage{float} # Table position
  - \restylefloat{table} # Not transfer table to a new page
---

# Логическое следствие и метод резолюций

**ИДЗ 5**

**Вариант:** 16

**Фамилия, имя, отчество:** Андреев Егор Сергеевич

**Номер группы:** 8к43

## Список задач

1. Методом резолюций выясните истинно ли приведенное утверждение. Решите
   задачу, используя два метода: стратегия вычеркивания и лок-резолюция.

$$
A, C \lor \neg A, \neg D \lor \neg A \lor \neg C \models \neg D \land A
$$

2. Записать хорновские дизъюнкты (5 штук), используя 3 литерала. Применяя табличный метод резолюций к хорновским дизъюнктам, установить истинно ли приведенное утверждение.

## Задача 1

### Условие задачи

Методом резолюций выясните истинно ли приведенное утверждение. Решите
задачу, используя два метода: стратегия вычеркивания и лок-резолюция.

$$
A, C \lor \neg A, \neg D \lor \neg A \lor \neg C \models \neg D \land A
$$

### Решение стратегией вычеркивания
```{=latex}
\setcounter{equation}{0}
\begin{align}
S^0: \notag \\
& A \\
& C \lor \neg A \\
& \neg D \lor \neg A \lor \neg C \\
S^1: \notag \\
& C \quad \text{из (1) и (2)} \\
& \neg D \lor \neg C \quad \text{ из (1) и (3)} \\
S^2: \notag \\
& \neg D \text{ из (4) и (5)}
S^3: \notag \\
& \neg D \land A \text{ из (1) и (6)}
\end{align}
```

### Решение лок-резолюцией
```{=latex}
\setcounter{equation}{0}
\begin{align}
& A \notag \\
& C \lor \neg A \notag \\
& \neg D \lor \neg A \lor \neg C \notag \\
& \text{Проведём следующую индексацию:} \notag \\
& _1 A  \\
& _2 C \lor _3 \neg A  \\
& _4 \neg  D \lor  _5 \neg A \lor _6 \neg  C \\
& \text{Из (1) - (3) получаем:} \notag \\
& _2 C \text{ из (1) и (2)} \\
& _4 \neg D \lor _6 \neg C \text{ из (1) и (3)} \\
& \text{Из (4) и (5) получаем:} \notag \\
& _4 \neg D \text{ из (4) и (5)} \\
\end{align}
```

## Задача 2

### Условие задачи

Записать хорновские дизъюнкты (5 штук), используя 3 литерала. Применяя табличный метод резолюций к хорновским дизъюнктам, установить истинно ли приведенное утверждение.

### Решение

Я не понял откуда брать дизъюнкты и по этому взял просто 5 **каких-то** дизъюнктов.

| № итерации | $S^n$ |  Дизъюнкты                                                                             |
| ---------- | ----- | ------------------ | ------------------ | -------------------- | --------- | --------- |
| 0          | $S^0$ | $\neg A \lor B$ *  | $\neg B \lor C$    | $\neg C \lor A$ *    | $B$       | $C$       |    
| 1          | $S^1$ | $B$ *              | $\neg B \lor C$ *  | $\neg C \lor A$      | $B$ *     | $C$       |
| 2          | $S^2$ | $B$                | $C$ *              | $\neg C \lor A$ *    | $B$       | $C$ *     |   
| 3          | $S^3$ | $B$                | $C$                | $A$                  | $B$       | $C$       |        

Дизъюнкты непротиворечивы
