---
author: "Андреев Егор Сергеевич"
format:
  pdf:
    include-in-header:
      text: |
mainfont: Liberation Serif
sansfont: Liberation Sans
monofont: Liberation Mono
fontsize: "14"
header-includes:
  - \usepackage{tabularx}
  - \usepackage[a4paper,top=2cm,bottom=2cm,left=3cm,right=1.5cm]{geometry}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{indentfirst}
  - \setlength{\parindent}{2em}
  - \renewcommand{\theequation}{\arabic{equation}}
  - \usepackage{fancyhdr}
  - \setlength{\footskip}{1cm}
  - \pagestyle{fancy}
  - \fancyhf{}
  - \fancyfoot[R]{\thepage}
  - \renewcommand{\headrulewidth}{0pt}
  - \renewcommand{\footrulewidth}{0pt}
execute:
  echo: false
---

\begin{titlepage}

\begin{center}

\textbf{МИНИСТЕРСТВО ОБРАЗОВАНИЯ И НАУКИ РОССИЙСКОЙ ФЕДЕРАЦИИ}

Федеральное государственное автономное образовательное учреждение высшего образования

\textbf{«НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ ТОМСКИЙ ПОЛИТЕХНИЧЕСКИЙ УНИВЕРСИТЕТ»}
\end{center}

Инженерная школа информационных технологий и робототехники


03.03.02 «Физика»

\vspace*{5cm}

\begin{center}

\textbf{ИЗУЧЕНИЕ ВНЕШНЕГО ФОТОЭФФЕКТА}

ЛАБОРАТОРНАЯ РАБОТА № 3-19


по дисциплине:

\textbf{Физика 3.8}

\end{center}

\vspace*{3cm}

\begin{tabular}{l l l}
Выполнил: \\ 
Cтудент группы 8к43 & Андреев Егор Сергеевич & 18.03.2026 \\
Проверил: \\
Ассистент отделения экспериментальной физики (ИЯТШ): & Калинич Иван \\
\end{tabular}

\vspace*{\fill}

\begin{center}
Томск – 2026
\end{center}

\end{titlepage}

**Цель работы:** снятие вольт-амперной характеристики фотоэлемента, определение красной границы фотоэффекта, работы выхода электрона и постоянной Планка, проверка законов Столетова.

**Приборы и принадлежности:** вакуумный фотоэлемент, галогеновая лампа, набор светофильтров, электронный блок приборов.

## Краткое теоретическое введение

Внешним фотоэффектом называют процесс испускания электронов с поверхности металла под действием света. Фотоэффект был подробно изучен в период с 1888 по 1889 гг. Александром Григорьевичем Столетовым, который установил, что испускаемые под действием света с поверхности вещества частицы имеют отрицательный знак.

### **Законы фотоэффекта (по Столетову)**
1. **1-й закон**: Сила фототока насыщения прямо пропорциональна интенсивности светового излучения.
2. **2-й закон**: Максимальная кинетическая энергия выбиваемых светом электронов возрастает с частотой света и не зависит от его интенсивности.
3. **3-й закон**: Для каждого вещества при определённом состоянии его поверхности существует **граничная частота света**, ниже которой фотоэффект не наблюдается. Эта частота и соответствующая ей длина волны называется **красной границей фотоэффекта**.

**Особенность фотоэффекта**: он является безынерционным явлением – не обнаруживается запаздывание в появлении вылетающих частиц в интервале $10^{-10}$ с после начала освещения.

### **Квантовая теория фотоэффекта**
Согласно квантовой теории, всякое тело может поглощать и испускать энергию порциями – **квантами энергии**. Энергия фотона $\varepsilon$ определяется по формуле Планка:

\begin{equation}
\varepsilon = h \nu,
\end{equation}

где:
- $h = 6,624 \cdot 10^{-34}$ Дж·с – **постоянная Планка**,
- $\nu$ – частота света.

Закон сохранения энергии при неупругом взаимодействии фотона со свободным электроном металла выражается **уравнением Эйнштейна**:

\begin{equation}
h \nu = A + \frac{m V_{\max}^2}{2},
\end{equation}

где:
- $A$ – **работа выхода** (минимальная энергия, необходимая для освобождения электрона из металла),
- $\frac{m V_{\max}^2}{2}$ – максимальная кинетическая энергия фотоэлектрона.

Из уравнения видно, что максимальная кинетическая энергия фотоэлектрона зависит от частоты света и работы выхода, но не от его интенсивности.

При уменьшении частоты света скорость выбитых электронов снижается. При некоторой частоте $\nu_0$ скорость становится равной нулю. Частоту $\nu_0$, ниже которой фотоэффект у данного металла не наблюдается, называют **красной границей фотоэффекта**:

\begin{equation}
h \nu_0 = A.
\end{equation}

### **Особенности фотоэлементов**
Особенности фотоэлементов определяются их **световой** и **вольт-амперной характеристиками**.

- **Световая характеристика**: зависимость силы фототока от величины падающего светового потока при постоянном напряжении между электродами.
- **Вольт-амперная характеристика (ВАХ)**: зависимость фототока от разности потенциалов между электродами при постоянном световом потоке.

## Ход работы

### Таблица 1. Вольт-амперные характеристики

\begin{tabularx}{\textwidth}{|c|*{10}{X|}}
\hline
\multicolumn{11}{|c|}{$\lambda = 480\,\text{нм}$} \\
\hline
$U$, В & $-0,8$ & $0$ & $1,0$ & $2,0$ & $3,0$ & $5,0$ & $8,0$ & $12,0$ & $16,0$ & $19,0$ \\
\hline
$I$, мкА & $0$ & $0,06$ & $0,29$ & $0,53$ & $0,68$ & $0,82$ & $0,93$ & $1,01$ & $1,03$ & $1,03$ \\
\hline
\end{tabularx}

```{python}
import matplotlib.pyplot as plt

U = [-0.8, 0, 1.0, 2.0, 3.0, 5.0, 8.0, 12.0, 16.0, 19.0]
I = [0, 0.06, 0.29, 0.53, 0.68, 0.82, 0.93, 1.01, 1.03, 1.03]

plt.plot(U, I, marker='o')
plt.xlabel("U, В")
plt.ylabel("I, мкА")
plt.title("I = f(U)")
plt.grid(True)

plt.suptitle("(рис. 1)", y=-0.025)
plt.legend()
plt.show()
```

**Вывод:**

При увеличении напряжения фототок сначала быстро растёт, затем достигает насыщения (около 1.03 мкА). Это подтверждает 1-й закон Столетова: сила фототока насыщения пропорциональна интенсивности светового потока.

Наличие горизонтального участка на графике указывает на то, что все выбитые электроны достигают анода, и дальнейшее увеличение напряжения не влияет на фототок. Это соответствует теоретическим представлениям о насыщении фототока.

### Таблица 2. Зависимость запирающего напряжения от частоты падающего света

\begin{tabularx}{\textwidth}{|c|*{5}{X|}}
\hline
Цвет светофильтра & Жел. & Зел. & Голуб. & Син. & Фиол. \\
\hline
$\lambda$, нм & 540 & 530 & 505 & 490 & 480 \\
\hline
$v \cdot 10^{14}$ Гц & 5,5  & 5,6 & 5,9 & 6,1 & 6,3 \\
\hline
$U_3$, В & -0,24 & -0,32 & -0,42 & -0,47 & -0,57 \\
\hline
$U_3$, В & -0,27 & -0,32 & -0,44 & -0,49 & -0,57 \\
\hline
$U_3$, В & -0,3 & -0,32 & -0,46 & -0,51 & -0,57 \\
\hline
$\bar{U}_3$, В & -0,27 & -0,32 & -0,44 & -0,49 & -0,57  \\
\hline
\end{tabularx}

```{python}
import numpy as np
import matplotlib.pyplot as plt

nu = np.array([5.5, 5.6, 5.9, 6.1, 6.3]) * 1e14  # Гц
U = np.array([-0.27, -0.32, -0.44, -0.49, -0.57])  # В

a, b = np.polyfit(nu, U, 1)

nu_line = np.linspace(0, max(nu)*1.1, 200)
U_line = a * nu_line + b

nu0 = -b / a

U0 = b

plt.figure(figsize=(7, 5))
plt.scatter(nu, U, label="Эксперимент", color="red")
plt.plot(nu_line, U_line, label="Среднее", color="blue")

plt.axhline(0, color="black", linewidth=1)
plt.axvline(0, color="black", linewidth=1)

plt.scatter([nu0], [0], color="green", label=f"ν0 ≈ {nu0:.2e} Гц")
plt.scatter([0], [U0], color="purple", label=f"U3(A/e) ≈ {U0:.2f} В")

plt.xlabel("Частота ν, Гц")
plt.ylabel("Задерживающее напряжение U₃, В")
plt.title("U₃ = f(ν)")
plt.suptitle("(рис. 2)", y=-0.025)

plt.legend()
plt.grid()
plt.tight_layout()


plt.show()
```

$$
\nu_0 \approx 4.74*10^14 Гц
$$

$$
U_3(\nu) \approx 1.73 В
$$

$$
A = U_3*e (эВ) = 1,73*1,6*10^{-19} \approx 2.8*10^-19
$$

$$
h = A/v_0 = 2.8*10^-19/4.74*10^14 \approx 0.59*10^-34
$$

$$
\delta_h = \frac{|h_{\text{эксп}} - h_{\text{табл}}|}{h_{\text{табл}}} \cdot 100\% = \frac{|5.84 \cdot 10^{-34} - 6.624 \cdot 10^{-34}|}{6.624 \cdot 10^{-34}} \cdot 100\% \approx 11.84\%
$$

**Вывод:**

Экспериментальная зависимость задерживающего напряжения U3U_3U3​ от частоты падающего света ν\nuν (рис. 2) представлена линейной функцией, что подтверждает уравнение Эйнштейна для фотоэффекта.

Постоянная Планка близка к табличному значению, что подтверждает корректность эксперимента.
Относительная погрешность в 11.8%обусловлена погрешностями измерений и неидеальностью установки.


### Таблица 3. Зависимость фототока от расстояния источника света до фотоэлемента

\begin{tabularx}{\textwidth}{|c|*{5}{X|}}
\hline
$r$, м &0,3  & 0,325 & 0,35 & 0,375 & 0,4 \\
\hline
$\frac{1}{r^2}$, м$^{-2}$11,1 & 9,5 & 8,2 & 7,1 & 6,3 &  \\
\hline
$I_{\phi}$, мкА & 2,7 & 2,32 & 2,07 & 1,93 & 1,77 \\
\hline
\end{tabularx}

```{python}
import numpy as np
import matplotlib.pyplot as plt

r = np.array([0.3, 0.325, 0.35, 0.375, 0.4])
I_phi = np.array([2.7, 2.32, 2.07, 1.93, 1.77])

x = 1 / (r**2)

plt.figure()
plt.plot(x, I_phi, marker='o')

plt.xlabel("1/r^2 (м^-2)")
plt.ylabel("Iφ (мкА)")
plt.title("Iφ = f(1/r^2)")
plt.grid(True)
plt.suptitle("(рис. 3)", y=-0.025)

plt.show()
```

**Вывод:**

График зависимости фототока представляет собой практически прямую линию, что подтверждает 2-й закон Столетова: сила фототока пропорциональна интенсивности светового потока, которая, в свою очередь, обратно пропорциональна квадрату расстояния от источника до фотоэлемента.

Нелинейные отклонения на больших расстояниях могут быть связаны с погрешностями измерений или неравномерностью освещённости.

### 4.Зависимость тока насыщения от светофильтров

\begin{tabularx}{\textwidth}{|c|*{5}{X|}}
\hline
Цвет светофильтра & Жел. & Зел. & Голуб. & Син. & Фиол. \\
\hline
$\lambda$, нм & 540 & 530 & 505 & 490 & 480 \\
\hline
$I_{нас}$, мкА & 19,0  & 13,7 & 11,5 & 9 & 13,23 \\
\hline
\end{tabularx}

```{python}
import matplotlib.pyplot as plt

lambda_nm = [540, 530, 505, 490, 480]
I = [19.0, 13.7, 11.5, 9.0, 13.23]

plt.figure()
plt.plot(lambda_nm, I, marker="o")

plt.xlabel("λ (нм)")
plt.ylabel("I (мкА)")
plt.title("Зависимость I = f(λ)")
plt.grid()
plt.suptitle("(рис. 4)", y=-0.025)

plt.show()
```

**Вывод:**

Ток насыщения нелинейно уменьшается с уменьшением длины волны (увеличением частоты) для большинства светофильтров, кроме фиолетового (480 нм), где наблюдается аномальное увеличение. Это может быт связано с погрешностью в измерениях.
